### ISSUE TITLE
Use `NotRequired[]` instead of `Optional[]` when a key can be missing in a `TypedDict`

### ISSUE THREAD

**Issue by MaT-PT** [Gowee/json2pyi#7]
Currently, when a dictionary has a key that can be missing, json2pyi produces a `TypedDict` with the key marked as `Optional[]`.

For example, the following JSON:
```json
[
    {"id": 1, "value": "foo", "comment": "bar"},
    {"id": 2, "value": null}
]
```
Produces this code:
```python
from __future__ import annotations

from typing import TypedDict, List, Optional

class UnnammedType160B90(TypedDict):
    id: int
    value: Optional[str]
    comment: Optional[str]
```

This is a problem, as `Optional[]` means the value is _required_, but can be `None` (`null` in JSON).
This is different from not being required.
In the previous example, the `comment` field is either missing, or is a `str`, but it cannot be `null`.

Python 3.11 introduced the `NotRequired[]` type qualifier to mark such potentially-missing keys (_cf._ [PEP 655](https://peps.python.org/pep-0655/)).

The code produced by json2pyi should then be:
```python
from __future__ import annotations

from typing import TypedDict, List, Optional, NotRequired

class UnnammedType160B90(TypedDict):
    id: int
    value: Optional[str]
    comment: NotRequired[str]
```
Which correctly marks `value` as nullable, and `comment` as potentially-missing.

**Comment by Gowee** [comment]
Great thanks for bringing that up!  Updated and deployed.
